### ISSUE TITLE
[Y1-6-2(기차-무지개)] 나레이션 교체 및 수정

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#1]
**1. 개념문제 :** 기차 달리는 화면 도기 나레이션 교체 (ex : 사과사과 > 머리머리)
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시

사운드 리스트 위치 : \\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계
한글 Y1,Y2 1~10 녹음_210225.xslx

**2. 도기 정답 맞췄을 때 na :** 야호! 하는 나레이션 대신 잘했어, 최고야가 들어가야 합니다.
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시
K_Y1_06_do_32, K_Y1_06_do_33 교체 두개만 나오도록 교체

**3. 개념문제 도기 오답 na :** K_Y1_06_do_31 교체

**4.** 문제 화면에서 정답 맞춘 후에 연기가 화면을 덮는 트렌지션 연출이 나오지 않음 > 연기가 화면을 덮는 트렌지션 연출이 나오도록 수정

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y1-6-2/Intro/
http://morphkr.synology.me/~jh.kim/20210225/Y1-6-2/Outro/
http://morphkr.synology.me/~jh.kim/20210225/Y1-6-2/Question1/
http://morphkr.synology.me/~jh.kim/20210225/Y1-6-2/Question2/
http://morphkr.synology.me/~jh.kim/20210225/Y1-6-2/Question3/
http://morphkr.synology.me/~jh.kim/20210225/Y1-6-2/Question4/
