### ISSUE TITLE
[Y1-6-3(상상하기)]사운드 교체 관련 수정내용 및 추가 수정내용

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#11]
1. 각 원화 선택 시 나오는 내레이션 교체
- 내레이션 파일 위치 : \\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계
- 내레이션 리스트 확인 : 한글 Y1 1~10, Y2 2 3 5 6 8 9 10 녹음(진짜 최종)_210225.xlsx

![image](https://user-images.githubusercontent.com/63280726/109611859-3922c400-7b72-11eb-8bd5-95d1ffef3353.png)

2. 가이드 애니메이션에 나오는 캐릭터 내레이션 파일 교체 (파일은 1번과 동일한 위치에 있음)
![image](https://user-images.githubusercontent.com/63280726/109612415-07f6c380-7b73-11eb-8d6f-78d3ae77774b.png)

3. BGM 루프되도록 수정
4. 머리 낱말 위치 아래 이미지와 같은 위치로 수정
![image](https://user-images.githubusercontent.com/63280726/109620287-0d590b80-7b7d-11eb-83b7-72a91a1f2006.png)

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210302/Y1-6-3/Y1-6-3.html

수정반영 완료 하였습니다.

**Comment by ParkHyunjung97** [comment]
머리, 손, 발 애니메이션 수정 진행 중입니다. 수정된 애니메이션 전달 받은 이후에 이슈 Close하겠습니다.
