### ISSUE TITLE
[Y2-9-3(상상하기)]사운드 교체 관련 수정내용

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#15]
1. 각 원화 선택 시 나오는 내레이션 교체
- 내레이션 파일 위치 : \\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계
- 내레이션 리스트 확인 : 한글 Y1 1~10, Y2 2 3 5 6 8 9 10 녹음(진짜 최종)_210225.xlsx
![image](https://user-images.githubusercontent.com/63280726/109614041-62911f00-7b75-11eb-9d19-f4cc6053ca93.png)

2. 가이드 애니메이션에 나오는 캐릭터 내레이션 파일 교체 (파일은 1번과 동일한 위치에 있음)
![image](https://user-images.githubusercontent.com/63280726/109612415-07f6c380-7b73-11eb-8d6f-78d3ae77774b.png)

3. BGM 루프되도록 수정

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210302/Y2-9-3/Y2-9-3.html

수정반영 완료 하였습니다.
