### ISSUE TITLE
[Y1-3-3(상상하기)] 사운드 관련 수정 내용

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#16]
- BGM 루프 되도록 수정

**Comment by jihoons94** [comment]
+ 가이드 나레이션 변경

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210302/Y1-3-3/Y1-3-3.html

수정반영 완료 하였습니다.
