### ISSUE TITLE
[Y1-3-2(기차-무지개)] 나레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#2]
1. 도기 정답 맞췄을 때 na 교체: 
\nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시
K_Y1_06_do_32, K_Y1_06_do_33 

2. 도기 오답 na 교체 : K_Y1_06_do_31 교체

**Comment by jihoons94** [comment]
/Work/_Project_2020/60.천재교과서/60_2.한글/#Resource/Sound(캐릭터,음원)/01.Y단계/1단계/Y1-6차시

**Comment by ParkHyunjung97** [comment]
Question1 기차 지나가는 씬에서 개념 사과 문제로 나오는데, 문제 화면에서는 바나나 듣기 문제로 출력됩니다
문제화면에서 사과 개념 문제로 나올 수 있도록 수정 부탁드립니다.
보기 순서 : (1) 포도 (2)수박 (3)사과

**Comment by ParkHyunjung97** [comment]
Question4 기차 문제 : 문제 화면 바나나 보기 없음
보기 순서 : (1)바나나 (2)사과 (3)수박

**Comment by jihoons94** [comment]
Question1 
![image](https://user-images.githubusercontent.com/36064039/109149979-98b45480-77ab-11eb-9ad0-62cc5745cc9d.png)

Question4
![image](https://user-images.githubusercontent.com/36064039/109150052-aff34200-77ab-11eb-8ff9-1c8132b52a72.png)

수정하였습니다
