### ISSUE TITLE
[Y1-9-2(기차-무지개)]나레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#3]
**1. 개념문제 :** 기차 달리는 화면 도기 나레이션 교체 (ex : 사과사과 > 소소소소)
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-9차시

**2. 도기 정답 피드백 na 교체  :** \nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시
K_Y1_06_do_32, K_Y1_06_do_33

**3. 도기 오답 na 교체 :** K_Y1_06_do_31 교체

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y1-9-2/Intro/
http://morphkr.synology.me/~jh.kim/20210225/Y1-9-2/Outro/
http://morphkr.synology.me/~jh.kim/20210225/Y1-9-2/Question1/
http://morphkr.synology.me/~jh.kim/20210225/Y1-9-2/Question2/
http://morphkr.synology.me/~jh.kim/20210225/Y1-9-2/Question3/
http://morphkr.synology.me/~jh.kim/20210225/Y1-9-2/Question4/

**Comment by ParkHyunjung97** [comment]
Question1 보기 수정 : (1) 사자 (2) 소 (3)오리

**Comment by ParkHyunjung97** [comment]
Question2 보기 수정 : (1)사자 (2)오리 (3)개

**Comment by ParkHyunjung97** [comment]
Question3 보기 수정 (문제 오리) : (1) 개 (2) 오리 (3) 소

**Comment by ParkHyunjung97** [comment]
Question4 보기 수정 (문제 개) : (1)개 (2)소 (3)사자

**Comment by jihoons94** [comment]
Q1
![01](https://user-images.githubusercontent.com/36064039/109154018-0e6eef00-77b1-11eb-8c1f-574fb1cc2cbe.PNG)

Q2
![02](https://user-images.githubusercontent.com/36064039/109154037-1464d000-77b1-11eb-8e72-1d97f724c1fd.PNG)

Q3
![03](https://user-images.githubusercontent.com/36064039/109154050-1890ed80-77b1-11eb-9ad5-df38b3f4448f.PNG)

Q4
![image](https://user-images.githubusercontent.com/36064039/109154058-1cbd0b00-77b1-11eb-93c3-6e4db2fef0a4.png)
