### ISSUE TITLE
[Y2-3-2(기차-숲속)]나레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#4]
**1. 도기 정답 맞췄을 때 na 교체:**
\nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시
K_Y1_06_do_32, K_Y1_06_do_33

**2. 도기 오답 na 교체 :** K_Y1_06_do_31 교체

**3. 문제별 사운드 교체 (개념, 듣기 모두) :** 

**4. 기차 달리는 화면 도기 나레이션 교체** (ex : 사과사과 > 무무무무)
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-3차시

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y2-3-2/Intro/
http://morphkr.synology.me/~jh.kim/20210225/Y2-3-2/Outro/
http://morphkr.synology.me/~jh.kim/20210225/Y2-3-2/Question1/
http://morphkr.synology.me/~jh.kim/20210225/Y2-3-2/Question2/
http://morphkr.synology.me/~jh.kim/20210225/Y2-3-2/Question3/
http://morphkr.synology.me/~jh.kim/20210225/Y2-3-2/Question4/

**Comment by ParkHyunjung97** [comment]
Question4 문제 보기 수정 (문제 토마토) : (1)고추 (2)무 (3)토마토

**Comment by jihoons94** [comment]
Q4
![image](https://user-images.githubusercontent.com/36064039/109154244-5f7ee300-77b1-11eb-852f-cc0cb6488b9e.png)
