### ISSUE TITLE
[Y2-6-2(기차-숲속)] 내레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#5]
1. 도기 정답 맞췄을 때 na 교체:
\nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시
K_Y1_06_do_32, K_Y1_06_do_33

2. 도기 오답 na 교체 : K_Y1_06_do_31 교체

3. 문제화면 별 사운드 교체 (개념, 듣기 모두) : \\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-6차시

4. 기차 달리는 화면 도기 나레이션 교체 (ex : 사과사과 > 무무무무)
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-6차시

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y2-6-2/Intro/
http://morphkr.synology.me/~jh.kim/20210225/Y2-6-2/Outro/
http://morphkr.synology.me/~jh.kim/20210225/Y2-6-2/Question1/
http://morphkr.synology.me/~jh.kim/20210225/Y2-6-2/Question2/
http://morphkr.synology.me/~jh.kim/20210225/Y2-6-2/Question3/
http://morphkr.synology.me/~jh.kim/20210225/Y2-6-2/Question4/

**Comment by ParkHyunjung97** [comment]
Question4 문제 수정 : 문제가 "나"인데 보기에 "나"가 없습니다. 수정 부탁드려요

**Comment by jihoons94** [comment]
![1614253698](https://user-images.githubusercontent.com/36064039/109149402-d9f83480-77aa-11eb-9198-445024620cea.png)
수정되었습니다.
