### ISSUE TITLE
[Y2-9-2(기차-숲속)] 내레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#6]
**1. 도기 정답 맞췄을 때 na 교체 :**
\nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\1단계\Y1-6차시
K_Y1_06_do_32, K_Y1_06_do_33

**2. 도기 오답 na 교체 :** K_Y1_06_do_31 교체

**3. 문제화면 별 사운드 교체 (개념, 듣기 모두) :** \nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-9차시

**4. 기차 달리는 화면 도기 나레이션 교체** (ex : 사과사과 > 무무무무)
\nas\Work_Project_2020\60.천재교과서\60_2.한글#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-9차시

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y2-9-2/Intro/
http://morphkr.synology.me/~jh.kim/20210225/Y2-9-2/Outro/
http://morphkr.synology.me/~jh.kim/20210225/Y2-9-2/Question1/
http://morphkr.synology.me/~jh.kim/20210225/Y2-9-2/Question2/
http://morphkr.synology.me/~jh.kim/20210225/Y2-9-2/Question3/
http://morphkr.synology.me/~jh.kim/20210225/Y2-9-2/Question4/

**Comment by ParkHyunjung97** [comment]
링크에 Outro가 나오지 않습니다. 확인 부탁드립니다

**Comment by jihoons94** [comment]
json 문제로 수정 완료하였습니다
