### ISSUE TITLE
[Y2-5-2(정,오답 DB - 우주행성)] 내레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#7]
1. 문제별 na 교체
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-5차시

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y2-5-2/
