### ISSUE TITLE
[Y2-8-2(정,오답 DB - 문)] 내레이션 교체

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#8]
1. 문제별 내레이션 교체
\\nas\Work\_Project_2020\60.천재교과서\60_2.한글\#Resource\Sound(캐릭터,음원)\01.Y단계\2단계\Y2-9차시
![image](https://user-images.githubusercontent.com/63280726/109121597-cb018a00-778a-11eb-9c31-cea527cd13ed.png)

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y2-8-2/
