### ISSUE TITLE
[Y1-3-1(코딩동화)] 동화 페이지 넘길 때 사운드 추가

### ISSUE THREAD

**Issue by ParkHyunjung97** [MorphKR/CJ_Milk-T_Kids_Hangul#9]
1. 동화 페이지 넘길 때 들리던 '휙' 하던 사운드가 사라짐 > 스와이프하여 동화 페이지 넘길 때 '휙'하는 사운드 추가

- 사운드 위치 : \\nas\Share\#2020\10.천재교과서\02.한글앱\Resource\효과음, BGM\Y1-3-1(코딩동화)
- 사운드 파일 : knife_throw_01.mp3

**Comment by jihoons94** [comment]
http://morphkr.synology.me/~jh.kim/20210225/Y1-3-1/

**Comment by ParkHyunjung97** [comment]
휙 소리 볼륨 낮춰서 파일 재전달 드리겠습니다

**Comment by jihoons94** [comment]
사운드 교체 완료, 같은 url로 확인 가능합니다.
